### ISSUE TITLE
Clear, minimal configuration file example

### ISSUE THREAD

**Issue by mactyr** [energyPATHWAYS/energyPATHWAYS#1]
As a novice developer
I want the example configurations.INI to contain only programmatically meaningful, well-described items
so that I can learn the configuration options efficiently.

**AC**
1. All obsolete fields (e.g. the ones under "[vintage]") are removed from the file.
2. Each field is preceded with a comment describing what it does and/or some other illustrative example values to try out. (This presumes that the config file format supports comments; if not this may need to be discarded.)

**Comment by ryandrewjones** [comment]
Good suggestion. A hashtag # can be used for comments: https://docs.python.org/2/library/configparser.html

**Comment by ryandrewjones** [comment]
Assigning to @BenHaleyEvolvedEnergyResearch for checking branch clear_config_1
