### ISSUE TITLE
Normalize geography tables in database

### ISSUE THREAD

**Issue by mactyr** [energyPATHWAYS/energyPATHWAYS#14]
As a non-developer pathways user
I want the GeographyMap table to be normalized
so that I can use whatever geography layers are applicable to my geography, rather than having "us", "census division", etc. hard-coded in the column names

**AC**
1. GeographyMap and associated tables are updated so that a geographical slice can be formed out of arbitrary geographical layers, not just the ones currently named in the columns.

**Reference**

A (non-public) [Google sheet](https://docs.google.com/spreadsheets/d/18ZInU5WDP9TU4N-oGpRPniEM_bHg-vT81-eZhYAxTq8/edit) where we are hashing out how to approach this.

**Comment by mactyr** [comment]
@ryandrewjones, I believe this is solved in the above referenced commit (normalize_geo_14 branch) and you seem like the natural person to review it since I know Ben is extra busy right now. Note that this is based off of my postgres branch so it won't really make sense to merge it into master until the existing dispatch/postgres work is merged in.

**Comment by ryandrewjones** [comment]
I can't test yet until I get the new DB set up, but I went through the code and it looks good. Since you are seeing the behavior you expect, I'd say this is resolved.

**Comment by mactyr** [comment]
Ok, we'll call it ready to merge then. (And once it's merged, _then_ it'll be resolved :wink:)

**Comment by mactyr** [comment]
For the record, this was merged along with #12 in 8936ffa28ef50bac261c0f67b9c74450d174fa86 (though a couple of subsequent commits were needed for cleanup).
