### ISSUE TITLE
Document dispatch solver dependency

### ISSUE THREAD

**Issue by mactyr** [energyPATHWAYS/energyPATHWAYS#22]
As an energyPATHWAYS developer-user
I want all dependencies documented
so that I can get up and running with a minimum of hassle

Depends on having a dispatch-complete version for me to test against.

**AC**
1. Document in the readme that a solver (e.g. glpk) is required for dispatch (and therefore to run Pathways) and how to install it.

**Note**

Theres a library called pyomo (like AMPL) that's already in the install list. It packages problem and sends it to solver. glpk is the solver we're using (there are others as well) -- is there a python library that wraps the installation, or will people need to install it separately?

**Comment by mactyr** [comment]
Can work on this off of master. Try running energyPATHWAYS/dispatch/optimization/run_dispatch.py; it will require a solver.

**Comment by mactyr** [comment]
Ok, I think this is taken care of on branch document_solver_22. Please review and let me know what you think.

**Comment by ryandrewjones** [comment]
Michael this looks good. I added an extra line of detail in the README that younger me would have appreciated. The final step will be to merge this in with Ben's latest branch, which might be be a messy merge, but not too difficult.

As far a performance, on my surface pro 4 (i7 2.20GHz) the test case runs in 61 seconds with GLPK and 40 seconds with CBC. Based on some changes Ben and I made to the formulation yesterday on his branch, I'm hoping for a further speedup.

**Comment by mactyr** [comment]
Ok, cool. We both forgot to put the issue number in our commit messages, so for reference the commits for this are f28a100b9ffdc3926e3c9c17dbc48f812af00e95 and 857977a9eae6f801f5107db5226d1e46d5ef3322.

**Comment by ryandrewjones** [comment]
Great, and also for our records, I observed a number of other file changes during my git add that I believe were simply a function of rerunning the files in my environment. The results from the test, for example, probably should be added to gitignore. But for this commit, they should just be ignored.

**Comment by mactyr** [comment]
Merged in e0430535bef5e3eec754a163c763518cb519af0d; closing.
