### ISSUE TITLE
Drop unneeded system tables

### ISSUE THREAD

**Issue by mactyr** [energyPATHWAYS/energyPATHWAYS#28]
[Technical ticket, no story]

Aside from the CurrencyYears table (#23) there are a few others that aren't referenced and/or don't seem to have much semantic value and can be dropped to reduce clutter. As of this writing these include:
- [ ] DemandServiceDemandUnitTypes (need to verify with @BenHaleyEvolvedEnergyResearch)
- [ ] DemandEnergyMeasureTypes (need to verify with @BenHaleyEvolvedEnergyResearch)
- [x] DayHour (can replace with a check constraint on ShapesData.hour to ensure values are between 1 and 24)
- [x] Month (can replace with a check constraint on ShapesData.month to ensure values are between 1 and 12)
- [x] DemandUnitDenominators (may require minor code changes to hard-code these column names rather than looking them up)
- [x] DemandDriverColumns (may also require minor code changes to hard-code column names)
- [x] YearHour

**For discussion**
- It also seems dubious to maintain a time zones table since this list can generally easily be obtained from a time zone library and it's probably better to let the library we're using be the authoritative source.

**Comment by ryandrewjones** [comment]
All but the first two are resolved in ticket 39. The first two may not be necessary.

**Comment by mactyr** [comment]
We have agreed that the first two tables should be deleted. This will be taken care of as part of #39. Closing.
