### ISSUE TITLE
Calculate Years

### ISSUE THREAD

**Issue by BenEvolved** [energyPATHWAYS/energyPATHWAYS#29]
If I'm a user that enters inputs for years prior to when a supply node runs, this information is lost in clean timeseries. I want to extend the years of that supply node so that it incorporates that data. 

Ben

**Comment by BenEvolved** [comment]
Ryan has been assigned this issue because it was determined that this is an issue with clean_timeseries.

**Comment by ryandrewjones** [comment]
Ben, over to you, extended_year_clean_timeseries_29 should fix the issue.
