### ISSUE TITLE
Electricity dispatch integration with IO framework

### ISSUE THREAD

**Issue by ryandrewjones** [energyPATHWAYS/energyPATHWAYS#3]
As a user interested in the impact of deeply decarbonized energy systems on electricity
I want the electricity dispatch hooked up to the input-output framework on the supply side so that the dispatch is run for each modeled year and informs both capacity requirements and fuel use.

**AC**
1. Electricity dispatch is called seamlessly within the process of solving the supply side in each year
2. The user has some ability to control this dispatch from the database or config file
3. The user is prompted with status updates on the dispatch while it is being solved
4. Auxiliary outputs from the electricity sector dispatch are compiled and available for output. These might include (dispatch shapes, annual renewable curtailment, storage mileage, market prices, transmission flows, maximum peak load, impacts from flexible load, etc.)

**Comment by mactyr** [comment]
Depends on #5.

**Comment by mactyr** [comment]
@BenHaleyEvolvedEnergyResearch and @ryandrewjones agree that all work described in this ticket is actually being worked on other tickets, so it's not necessary. Closing.
