### ISSUE TITLE
Electricity dispatch accounting by demand sector

### ISSUE THREAD

**Issue by ryandrewjones** [energyPATHWAYS/energyPATHWAYS#5]
As a users particularly interested in the impacts of electrification on the distribution system
I would like to have the ability to account for residential, commercial, and industrial demand subsector distribution impacts separately so I can properly allocate costs and focus efforts for distribution upgrade deferral.

**AC**
1. User has the ability to allocate distribution subsectors to an arbitrary number of electricity distribution representations in the supply side dispatch. Transportation, for instance, could be allocated between feeders representing residential subsectors and commercial subsectors.
2. Each of the distribution feeders connects to the transmission system in the appropriate regions to support two way power flow.
3. Energy storage and flexible load capabilities are set up on each of the distribution feeders.

**Comment by BenEvolved** [comment]
Runs with test inputs from .csv on 3 distribution feeders and one bulk 'feeder'
